version: '3'
services: 
    serviio:
        build: .
        ports:
            - "1900:1900/udp"
            - "8895:8895/tcp"
            - "23423:23423/tcp"
            - "23523:23523/tcp"
            - "23424:23424/tcp"
            - "23524:23524/tcp"