version: '3.8'
services: 
    serviio:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                BUILD_DATE: "date -u +\"%Y-%m-%dT%H:%M:%SZ\""
                VCS_REF: "git rev-parse --short"
                VERSION: "2.1"
                FFMPEG_VERSION: "4.2"
                SERVIIO_VERSION: "2.1"
        image: sndsolutions/serviio:2.1
        network_mode: host
        container_name: serviio
        ports:
            - "1900:1900/udp"
            - "8895:8895/tcp"
            - "23423:23423/tcp"
            - "23424:23424/tcp"
            - "23523:23523/tcp"
            - "23524:23524/tcp"
        volumes:
            - "/mnt/user/appdata/serviio/library:/opt/serviio/library"
            - "/mnt/user/appdata/serviio/plugins:/opt/serviio/plugins"
            - "/mnt/user/appdata/serviio/log:/opt/serviio/log"
            - "/mnt/user/transcode:/tmp"
            - "/mnt/user/appdata/serviio/media:/media/serviio"